version: "3.3"

services:
  api:
    build: .
    command: npm run start:dev
    volumes:
     - ./src:/app/src
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql
    env_file:
      - ./mysql.env
